// <auto-generated />
using System;
using Lomtalanitas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lomtalanitas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219085345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Lomtalanitas.Models.Korzet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KorzetSzam")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("körzet_szám");

                    b.Property<DateTime>("LomtalanitasDatum")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lomtalanítás_dátum");

                    b.HasKey("Id");

                    b.ToTable("körzetek");
                });

            modelBuilder.Entity("Lomtalanitas.Models.Utcanev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KorzetId")
                        .HasColumnType("int")
                        .HasColumnName("körzet_id");

                    b.Property<string>("UtcaNev")
                        .HasColumnType("longtext")
                        .HasColumnName("utca_név");

                    b.HasKey("Id");

                    b.HasIndex("KorzetId");

                    b.ToTable("utcanevek");
                });

            modelBuilder.Entity("Lomtalanitas.Models.Utcanev", b =>
                {
                    b.HasOne("Lomtalanitas.Models.Korzet", "Korzet")
                        .WithMany("Utcanevek")
                        .HasForeignKey("KorzetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korzet");
                });

            modelBuilder.Entity("Lomtalanitas.Models.Korzet", b =>
                {
                    b.Navigation("Utcanevek");
                });
#pragma warning restore 612, 618
        }
    }
}
